export default {
  // home
  CHANGE_BALANCE: "CHANGE_BALANCE",
  CHANGE_INCOME: "CHANGE_INCOME",
  CHANGE_EXPENSE: "CHANGE_EXPENSE",
  CHANGE_SECTION_DATA: "CHANGE_SECTION_DATA",

  // income expense
  CHANGE_SELECTED: "CHANGE_SELECTED",
  CHANGE_DESCRIPTION: "CHANGE_DESCRIPTION",
  CHANGE_AMOUNT: "CHANGE_AMOUNT",
  CHANGE_ID: "CHANGE_ID",
  CHANGE_DATE: "CHANGE_DATE",
  CHANGE_SHOW: "CHANGE_SHOW",
};
